# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def available_pods
  # Pods for Speed Gauge
  pod 'Charts', '3.1.1'
  pod 'Surge', '2.0.0'
  pod 'SigmaSwiftStatistics', '7.0.2'
end

target 'Speed Gauge' do
  available_pods
end

target 'Speed Gauge Tests' do
  available_pods
end

post_install do |installer|
		installer.generated_projects.each do |project|
				project.targets.each do |target|
						target.build_configurations.each do |config|
								config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
						end
				end
		end
end
