# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def available_pods
  # Pods for Speed Gauge
  pod 'Charts'
  pod 'Surge'
end

target 'Speed Gauge' do
  available_pods
end

target 'Speed Gauge Tests' do
  available_pods
end
